---
metadata:
  name: IITM KB
  short_name: IITM KB
  description: A Student-made Knowledge Base for IITM Online B.Sc Degree
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/code.svg"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: Contact Me
      link: "mailto:biswasrahul016@gmail.com"
      external: true
    - text: Contact IITM Suppport
      link: "mailto:support@onlinedegree.iitm.ac.in"
      external: true
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/gettingstarted"
      title: ":school: Getting Started"
    - order: 2
      path: "/configuration"
      title: ":wrench: Configuration"
    - order: 3
      path: "/editing"
      title: ":writing_hand: Editing Content"
    - order: 4
      path: "/deployment"
      title: ":rocket: Deployment"
    - order: 5
      path: "/developing"
      title: ":computer: Developing"
  ignoreIndex: false
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

features:
  darkMode:
    enabled: true  
    default: false
  editOnRepo:
    location: https://github.com/filipowm/boogi 
    type: github
    editable: false
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: IITM KB
    showIcon: false
    copyright: "2021, Rahul Biswas"
    webMaster: "Rahul Biswas"
    managingEditor: "Rahul Biswas"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    indexName: 'IITM_OBSC_KB'
    algoliaAppId: '51YKLMANJN'
    algoliaSearchKey: '2f6eeeac03d6b05323096cfdacd997f8'
    algoliaAdminKey: '0b2d70399375e6cff2116d7eb1ca1616'
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
